TemplateDoesNotExist at /sessions/create/
sessions/create_advanced.html
Request Method:	GET
Request URL:	http://3e4c4c4a-b60b-4556-9647-2c6022f13499-00-186qnvr9j3jvh.worf.replit.dev/sessions/create/
Django Version:	5.2.1
Exception Type:	TemplateDoesNotExist
Exception Value:	
sessions/create_advanced.html
Exception Location:	/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/template/loader.py, line 19, in get_template
Raised during:	sessions.views.create_session
Python Executable:	/home/runner/workspace/.pythonlibs/bin/python
Python Version:	3.11.10
Python Path:	
['/home/runner/workspace',
 '/nix/store/lc7qv2ldzrs1aq3hbyzmbgvn0h2w26pl-sitecustomize/lib/python/site-packages',
 '/nix/store/dfg63lldbvcj207iyr9z0xw21d8ax02n-python3.11-pip-24.0/lib/python3.11/site-packages',
 '/nix/store/clx0mcir7qw8zk36zbr4jra789g3knf6-python3-3.11.10/lib/python311.zip',
 '/nix/store/clx0mcir7qw8zk36zbr4jra789g3knf6-python3-3.11.10/lib/python3.11',
 '/nix/store/clx0mcir7qw8zk36zbr4jra789g3knf6-python3-3.11.10/lib/python3.11/lib-dynload',
 '/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages',
 '/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages',
 '/nix/store/wblvmd5y7izx0z10d1w7ga7zc4apjxmb-python3.11-setuptools-75.1.1/lib/python3.11/site-packages']
Server time:	Mon, 26 May 2025 04:02:41 +0000
Template-loader postmortem
Django tried loading these templates, in this order:

Using engine django:

django.template.loaders.filesystem.Loader: /home/runner/workspace/templates/sessions/create_advanced.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/contrib/admin/templates/sessions/create_advanced.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/contrib/auth/templates/sessions/create_advanced.html (Source does not exist)
django.template.loaders.app_directories.Loader: /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/rest_framework/templates/sessions/create_advanced.html (Source does not exist)
Traceback Switch to copy-and-paste view
/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/core/handlers/exception.py, line 42, in inner
                response = await get_response(request)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^ â€¦
Local vars
/home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/django/core/handlers/base.py